# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'sergioisidoro'

branding:
  icon: 'box'
  color: 'green'

description: 'Push your strings automatically to Transifex when PR is ready for translations'

name: 'github-transifex-actions'

runs:
  using: 'docker'
  image: 'docker://sergioisidoro/github-transifex-action'
